import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Dogs - Crocchette (12 products)
        {
            name: 'Almo Nature Holistic Adult Large Chicken & Rice 12kg',
            price: 45.99,
            weight: '12kg',
            badge: 'Best Seller',
            rating: 4.8,
            category: 'Crocchette',
            subcategory: 'Adult',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Almo Nature',
            breed: 'Labrador',
            intolerances: [],
            tags: ['Naturale', 'Pollo', 'Riso'],
            ingredients: 'Pollo fresco (26%), riso (14%), mais, polpa di barbabietola, olio di pollo. Proteine: 26%',
            benefits: ['Proteine di alta qualità', 'Digestione facile', 'Pelo lucido'],
            contraindications: 'Non somministrare a cuccioli sotto i 12 mesi',
            usage: 'Cani adulti (25-35kg): 280-380g al giorno divisi in 2 pasti',
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'Royal Canin Labrador Retriever Adult 12kg',
            price: 65.99,
            weight: '12kg',
            badge: 'Veterinario Consigliato',
            rating: 4.9,
            category: 'Crocchette',
            subcategory: 'Breed Specific',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Royal Canin',
            breed: 'Labrador',
            intolerances: [],
            tags: ['Specifico per razza', 'Controllo peso'],
            ingredients: 'Riso, farina di pollame disidratata, mais, glutine di mais, grassi animali. Proteine: 30%',
            benefits: ['Controllo del peso', 'Salute articolare', 'Mantello idrorepellente'],
            contraindications: null,
            usage: 'Cani adulti Labrador: 320-420g al giorno in 2 pasti',
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: "Hill's Science Plan Adult Perfect Weight 12kg",
            price: 58.50,
            weight: '12kg',
            badge: 'Sconto 15%',
            rating: 4.6,
            category: 'Crocchette',
            subcategory: 'Weight Management',
            animal: 'Cani',
            age: 'adulto',
            brand: "Hill's",
            breed: 'Pastore Tedesco',
            intolerances: [],
            tags: ['Controllo peso', 'Scientifico'],
            ingredients: 'Pollo, riso integrale, piselli, polpa di barbabietola, olio di pesce. Proteine: 28%',
            benefits: ['Controllo del peso', 'Metabolismo sano', 'Sazietà prolungata'],
            contraindications: 'Non adatto a cuccioli in crescita',
            usage: 'Cani adulti (20-30kg): 240-330g al giorno divisi in 2 pasti',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Orijen Original Adult Dog 11.4kg',
            price: 89.99,
            weight: '11.4kg',
            badge: 'Premium',
            rating: 4.9,
            category: 'Crocchette',
            subcategory: 'Grain Free',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Orijen',
            breed: 'Golden Retriever',
            intolerances: ['Cereali'],
            tags: ['Grain Free', 'Biologico', 'Premium'],
            ingredients: 'Pollo fresco (15%), tacchino fresco (7%), pesce intero (4%), fegato di pollo (4%). Proteine: 38%',
            benefits: ['Alto contenuto proteico', 'Ingredienti freschi', 'Senza cereali'],
            contraindications: null,
            usage: 'Cani adulti (25kg): 240-320g al giorno in 2 pasti',
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Farmina N&D Grain Free Pumpkin Lamb 12kg',
            price: 72.50,
            weight: '12kg',
            badge: 'Novità',
            rating: 4.8,
            category: 'Crocchette',
            subcategory: 'Grain Free',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Farmina',
            breed: 'Border Collie',
            intolerances: ['Cereali', 'Pollo'],
            tags: ['Grain Free', 'Agnello', 'Zucca'],
            ingredients: 'Agnello fresco (20%), patate dolci, zucca (8%), olio di aringa, mirtilli. Proteine: 32%',
            benefits: ['Ipoallergenico', 'Digestione facile', 'Antiossidanti naturali'],
            contraindications: 'Non somministrare insieme ad altri alimenti',
            usage: 'Cani adulti (20-25kg): 200-280g al giorno in 2 pasti',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Eukanuba Adult Large Breed Chicken 12kg',
            price: 52.90,
            weight: '12kg',
            badge: null,
            rating: 4.5,
            category: 'Crocchette',
            subcategory: 'Large Breed',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Eukanuba',
            breed: 'Pastore Tedesco',
            intolerances: [],
            tags: ['Taglia grande', 'Pollo', 'Salute articolare'],
            ingredients: 'Pollo disidratato (23%), riso, mais, polpa di barbabietola, olio di pollo. Proteine: 26%',
            benefits: ['Salute articolare', 'Muscoli forti', 'Sistema immunitario'],
            contraindications: null,
            usage: 'Cani adulti taglia grande: 300-400g al giorno',
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            name: 'Acana Heritage Adult Large Breed 11.4kg',
            price: 78.90,
            weight: '11.4kg',
            badge: 'Premium',
            rating: 4.7,
            category: 'Crocchette',
            subcategory: 'Heritage',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Acana',
            breed: 'Labrador',
            intolerances: [],
            tags: ['Heritage', 'Naturale', 'Canadese'],
            ingredients: 'Pollo fresco (16%), farina di pollo (13%), patate rosse, piselli verdi. Proteine: 31%',
            benefits: ['Ingredienti regionali', 'Digestione ottimale', 'Energia sostenuta'],
            contraindications: null,
            usage: 'Cani adulti (25-35kg): 270-360g al giorno',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Purina Pro Plan Adult Large Athletic 14kg',
            price: 67.50,
            weight: '14kg',
            badge: 'Best Seller',
            rating: 4.6,
            category: 'Crocchette',
            subcategory: 'Athletic',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Purina Pro Plan',
            breed: 'Golden Retriever',
            intolerances: [],
            tags: ['Athletic', 'Performance', 'Taglia grande'],
            ingredients: 'Pollo (20%), riso, glutine di mais, grassi animali, polpa di barbabietola. Proteine: 30%',
            benefits: ['Performance atletica', 'Massa muscolare', 'Recupero rapido'],
            contraindications: 'Non adatto a cani sedentari',
            usage: 'Cani atletici (25-35kg): 350-450g al giorno',
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'Taste of the Wild Pacific Stream 12.2kg',
            price: 69.90,
            weight: '12.2kg',
            badge: 'Grain Free',
            rating: 4.8,
            category: 'Crocchette',
            subcategory: 'Wild',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Taste of the Wild',
            breed: 'Beagle',
            intolerances: ['Cereali'],
            tags: ['Grain Free', 'Salmone', 'Wild'],
            ingredients: 'Salmone (18%), farina di pesce (15%), patate dolci, piselli, olio di canola. Proteine: 25%',
            benefits: ['Omega-3 e 6', 'Gusto selvaggio', 'Pelo brillante'],
            contraindications: null,
            usage: 'Cani adulti (15-25kg): 200-320g al giorno',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'Monge Natural Superpremium Adult 12kg',
            price: 43.90,
            weight: '12kg',
            badge: null,
            rating: 4.4,
            category: 'Crocchette',
            subcategory: 'Natural',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Monge',
            breed: 'Border Collie',
            intolerances: [],
            tags: ['Naturale', 'Italiano', 'Superpremium'],
            ingredients: 'Pollo fresco (10%), riso (10%), mais, polpa di barbabietola, olio di pollo. Proteine: 26%',
            benefits: ['Prodotto italiano', 'Ingredienti naturali', 'Qualità premium'],
            contraindications: null,
            usage: 'Cani adulti (20-30kg): 250-350g al giorno',
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            name: 'Brit Premium Adult Large 15kg',
            price: 41.50,
            weight: '15kg',
            badge: 'Sconto 15%',
            rating: 4.3,
            category: 'Crocchette',
            subcategory: 'Premium',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Brit',
            breed: 'Pastore Tedesco',
            intolerances: [],
            tags: ['Premium', 'Taglia grande', 'Conveniente'],
            ingredients: 'Pollo disidratato (25%), riso, mais, grasso di pollo, polpa di barbabietola. Proteine: 24%',
            benefits: ['Rapporto qualità-prezzo', 'Taglia grande', 'Digestione facile'],
            contraindications: null,
            usage: 'Cani adulti taglia grande: 300-450g al giorno',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Trainer Natural Adult Maxi 12.5kg',
            price: 48.90,
            weight: '12.5kg',
            badge: null,
            rating: 4.5,
            category: 'Crocchette',
            subcategory: 'Natural',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Trainer',
            breed: 'Golden Retriever',
            intolerances: [],
            tags: ['Naturale', 'Maxi', 'Italiano'],
            ingredients: 'Pollo fresco (10%), riso integrale, mais, olio di pesce, erbe aromatiche. Proteine: 24%',
            benefits: ['Ingredienti naturali', 'Erbe benefiche', 'Made in Italy'],
            contraindications: null,
            usage: 'Cani adulti taglia grande: 280-380g al giorno',
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },

        // Dogs - Cibo Umido (8 products)
        {
            name: 'Almo Nature Classic Pollo e Prosciutto 280g',
            price: 3.90,
            weight: '280g',
            badge: null,
            rating: 4.7,
            category: 'Cibo Umido',
            subcategory: 'Classic',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Almo Nature',
            breed: null,
            intolerances: [],
            tags: ['Umido', 'Pollo', 'Prosciutto'],
            ingredients: 'Pollo (45%), prosciutto (5%), brodo di cottura. Proteine: 14%',
            benefits: ['Alto contenuto di carne', 'Idratazione', 'Gusto appetitoso'],
            contraindications: null,
            usage: 'Cani adulti (10-20kg): 1-2 lattine al giorno',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Royal Canin Adult Wet Food Chunks 400g',
            price: 4.50,
            weight: '400g',
            badge: 'Veterinario Consigliato',
            rating: 4.6,
            category: 'Cibo Umido',
            subcategory: 'Adult',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Royal Canin',
            breed: null,
            intolerances: [],
            tags: ['Chunks', 'Completo', 'Bilanciato'],
            ingredients: 'Carne e sottoprodotti (4%), cereali, oli e grassi, minerali. Proteine: 8%',
            benefits: ['Nutrizione completa', 'Consistenza appetitosa', 'Facile digestione'],
            contraindications: null,
            usage: 'Cani adulti (15kg): 1.5 lattine al giorno',
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            name: 'Cesar Delicatessen Agnello e Verdure 150g',
            price: 2.10,
            weight: '150g',
            badge: null,
            rating: 4.4,
            category: 'Cibo Umido',
            subcategory: 'Delicatessen',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Cesar',
            breed: null,
            intolerances: [],
            tags: ['Delicatessen', 'Agnello', 'Verdure'],
            ingredients: 'Agnello (4%), verdure (carote, piselli), brodo, minerali. Proteine: 9%',
            benefits: ['Gusto raffinato', 'Verdure benefiche', 'Porzione singola'],
            contraindications: null,
            usage: 'Cani piccoli: 1-2 vaschette al giorno',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Pedigree Adult Manzo in Gelatina 400g',
            price: 2.90,
            weight: '400g',
            badge: 'Best Seller',
            rating: 4.3,
            category: 'Cibo Umido',
            subcategory: 'Classic',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Pedigree',
            breed: null,
            intolerances: [],
            tags: ['Manzo', 'Gelatina', 'Conveniente'],
            ingredients: 'Carne e sottoprodotti (4% manzo), cereali, gelatina, minerali. Proteine: 8%',
            benefits: ['Prezzo conveniente', 'Consistenza gelatinosa', 'Facile digestione'],
            contraindications: null,
            usage: 'Cani adulti (15-25kg): 1-2 lattine al giorno',
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            name: 'Monge Fresh Salmone e Riso 100g',
            price: 1.95,
            weight: '100g',
            badge: 'Fresh',
            rating: 4.6,
            category: 'Cibo Umido',
            subcategory: 'Fresh',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Monge',
            breed: null,
            intolerances: [],
            tags: ['Fresh', 'Salmone', 'Riso'],
            ingredients: 'Salmone fresco (8%), riso (4%), brodo di pesce, verdure. Proteine: 10%',
            benefits: ['Salmone fresco', 'Omega-3', 'Ingredienti italiani'],
            contraindications: null,
            usage: 'Cani piccoli-medi: 2-3 vaschette al giorno',
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'Trainer Natural Adult Pollo e Riso 150g',
            price: 2.30,
            weight: '150g',
            badge: null,
            rating: 4.5,
            category: 'Cibo Umido',
            subcategory: 'Natural',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Trainer',
            breed: null,
            intolerances: [],
            tags: ['Natural', 'Pollo', 'Riso'],
            ingredients: 'Pollo (6%), riso (4%), brodo naturale, minerali, vitamine. Proteine: 9%',
            benefits: ['Ingredienti naturali', 'Made in Italy', 'Riso facilmente digeribile'],
            contraindications: null,
            usage: 'Cani medi: 2-3 vaschette al giorno',
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            name: 'Schesir Natural Tonno con Riso 285g',
            price: 3.20,
            weight: '285g',
            badge: 'Natural',
            rating: 4.7,
            category: 'Cibo Umido',
            subcategory: 'Natural',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Schesir',
            breed: null,
            intolerances: [],
            tags: ['Natural', 'Tonno', 'Riso'],
            ingredients: 'Tonno (52%), riso (1.5%), brodo di cottura. Proteine: 12%',
            benefits: ['Alto contenuto di pesce', 'Naturale al 100%', 'Rica di proteine'],
            contraindications: null,
            usage: 'Cani adulti (10-20kg): 1-2 lattine al giorno',
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Purina One Adult Manzo e Carote 390g',
            price: 3.80,
            weight: '390g',
            badge: null,
            rating: 4.4,
            category: 'Cibo Umido',
            subcategory: 'One',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Purina One',
            breed: null,
            intolerances: [],
            tags: ['One', 'Manzo', 'Carote'],
            ingredients: 'Carne e sottoprodotti (6% manzo), carote (1%), cereali, minerali. Proteine: 8.5%',
            benefits: ['Nutrizione bilanciata', 'Carote per la vista', 'Facile digestione'],
            contraindications: null,
            usage: 'Cani adulti (15-25kg): 1-2 lattine al giorno',
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },

        // Dogs - Snack (6 products)
        {
            name: 'Briantos Dental Sticks Medium 720g',
            price: 12.90,
            weight: '720g',
            badge: 'Dental',
            rating: 4.7,
            category: 'Snack',
            subcategory: 'Dental',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Briantos',
            breed: null,
            intolerances: [],
            tags: ['Dental', 'Igiene orale', 'Medium'],
            ingredients: 'Cereali, sottoprodotti di origine vegetale, carne e sottoprodotti, minerali. Proteine: 8%',
            benefits: ['Igiene dentale', 'Riduce tartaro', 'Alito fresco'],
            contraindications: 'Non somministrare a cuccioli sotto i 4 mesi',
            usage: '1 stick al giorno per cani di taglia media',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            name: 'Pedigree DentaStix Large 1080g',
            price: 15.90,
            weight: '1080g',
            badge: 'Best Seller',
            rating: 4.8,
            category: 'Snack',
            subcategory: 'Dental',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Pedigree',
            breed: null,
            intolerances: [],
            tags: ['DentaStix', 'Large', 'Pulizia denti'],
            ingredients: 'Cereali, sottoprodotti vegetali, minerali, carne (4%). Proteine: 9%',
            benefits: ['Pulizia profonda', 'Contro placca e tartaro', 'Gusto irresistibile'],
            contraindications: null,
            usage: '1 stick al giorno per cani taglia grande',
            createdAt: new Date('2024-03-03').toISOString(),
            updatedAt: new Date('2024-03-03').toISOString(),
        },
        {
            name: 'Whimzees Spazzolino Naturale Medium 12pz',
            price: 18.50,
            weight: '360g',
            badge: 'Naturale',
            rating: 4.9,
            category: 'Snack',
            subcategory: 'Natural Dental',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Whimzees',
            breed: null,
            intolerances: ['Cereali'],
            tags: ['Naturale', 'Vegetale', 'Spazzolino'],
            ingredients: 'Patate, glicerina, cellulosa, lecitina. Senza cereali e additivi artificiali. Proteine: 1%',
            benefits: ['100% vegetale', 'Lunga durata', 'Design funzionale'],
            contraindications: null,
            usage: '1 pezzo ogni 2-3 giorni per cani medi',
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            name: 'Trainer Treats Biscotti con Pollo 500g',
            price: 8.90,
            weight: '500g',
            badge: null,
            rating: 4.5,
            category: 'Snack',
            subcategory: 'Biscotti',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Trainer',
            breed: null,
            intolerances: [],
            tags: ['Biscotti', 'Pollo', 'Training'],
            ingredients: 'Cereali, carne e sottoprodotti (pollo 4%), oli e grassi. Proteine: 12%',
            benefits: ['Perfetti per addestramento', 'Gusto irresistibile', 'Facili da spezzare'],
            contraindications: null,
            usage: 'Max 10% della razione giornaliera',
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            name: 'Zuke's Mini Naturals Salmon 170g',
            price: 11.90,
            weight: '170g',
            badge: 'Premium',
            rating: 4.8,
            category: 'Snack',
            subcategory: 'Training',
            animal: 'Cani',
            age: 'adulto',
            brand: "Zuke's",
            breed: null,
            intolerances: ['Cereali'],
            tags: ['Mini', 'Salmone', 'Training'],
            ingredients: 'Salmone, patate dolci, glicerina, sale marino naturale. Proteine: 12%',
            benefits: ['Salmone selvaggio', 'Mini size per training', 'Grain free'],
            contraindications: null,
            usage: 'Perfetti per addestramento, 5-10 pezzi al giorno',
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            name: 'Rocco Chings Strips Anatra 200g',
            price: 9.50,
            weight: '200g',
            badge: 'Novità',
            rating: 4.6,
            category: 'Snack',
            subcategory: 'Strips',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Rocco',
            breed: null,
            intolerances: [],
            tags: ['Strips', 'Anatra', 'Masticabili'],
            ingredients: 'Anatra 95%, glicerina vegetale. Proteine: 55%',
            benefits: ['Alto contenuto di carne', 'Proteine premium', 'Texture morbida'],
            contraindications: null,
            usage: '2-5 strips al giorno come premio',
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },

        // Dogs - Integratori (2 products)
        {
            name: 'Forza10 Omega3 Active 60 Capsule',
            price: 24.90,
            weight: '60cps',
            badge: 'Veterinario Consigliato',
            rating: 4.7,
            category: 'Integratori',
            subcategory: 'Omega',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Forza10',
            breed: null,
            intolerances: [],
            tags: ['Omega3', 'Pelo', 'Cute'],
            ingredients: 'Olio di pesce (EPA 18%, DHA 12%), vitamina E, gelatina',
            benefits: ['Pelo lucido', 'Cute sana', 'Antinfiammatorio naturale'],
            contraindications: 'Consultare il veterinario se in terapia anticoagulante',
            usage: 'Cani fino 10kg: 1 capsula/die, oltre 10kg: 2 capsule/die',
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            name: 'Candioli Articolazioni Plus 240g',
            price: 35.50,
            weight: '240g',
            badge: 'Plus',
            rating: 4.8,
            category: 'Integratori',
            subcategory: 'Articolazioni',
            animal: 'Cani',
            age: 'senior',
            brand: 'Candioli',
            breed: null,
            intolerances: [],
            tags: ['Articolazioni', 'Glucosamina', 'Senior'],
            ingredients: 'Glucosamina solfato, condroitin solfato, MSM, collagene, vitamina C',
            benefits: ['Mobilità articolare', 'Cartilagini sane', 'Riduce dolore'],
            contraindications: null,
            usage: 'Cani fino 15kg: 1 misurino/die, oltre 15kg: 2 misurini/die',
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },

        // Dogs - Giochi (2 products)
        {
            name: 'Kong Classic Large Red',
            price: 15.90,
            weight: '200g',
            badge: 'Best Seller',
            rating: 4.9,
            category: 'Giochi',
            subcategory: 'Masticabili',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Kong',
            breed: null,
            intolerances: [],
            tags: ['Kong', 'Resistente', 'Large'],
            ingredients: 'Gomma naturale rossa ultra-resistente',
            benefits: ['Indistruttibile', 'Stimola mente', 'Riempibile con cibo'],
            contraindications: 'Controllare usura periodicamente',
            usage: 'Riempire con cibo o snack per stimolare il gioco',
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        {
            name: 'Nylabone DuraChew Power Chew Bacon',
            price: 12.50,
            weight: '150g',
            badge: 'Power',
            rating: 4.6,
            category: 'Giochi',
            subcategory: 'Masticabili',
            animal: 'Cani',
            age: 'adulto',
            brand: 'Nylabone',
            breed: null,
            intolerances: [],
            tags: ['DuraChew', 'Bacon', 'Power'],
            ingredients: 'Nylon resistente, aroma bacon naturale',
            benefits: ['Igiene dentale', 'Lunga durata', 'Gusto bacon'],
            contraindications: 'Solo per cani oltre 15kg',
            usage: 'Sostituire quando consumato per 1/4',
            createdAt: new Date('2024-03-22').toISOString(),
            updatedAt: new Date('2024-03-22').toISOString(),
        },

        // Cats - Crocchette (8 products)
        {
            name: 'Royal Canin Indoor 10kg',
            price: 49.90,
            weight: '10kg',
            badge: 'Best Seller',
            rating: 4.8,
            category: 'Crocchette',
            subcategory: 'Indoor',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Royal Canin',
            breed: 'Persiano',
            intolerances: [],
            tags: ['Indoor', 'Controllo odori', 'Pelo lungo'],
            ingredients: 'Proteine disidratate di pollame, riso, mais, grassi animali, polpa di barbabietola. Proteine: 27%',
            benefits: ['Controllo odori feci', 'Gestione boli di pelo', 'Peso ideale'],
            contraindications: null,
            usage: 'Gatti adulti indoor: 40-60g al giorno',
            createdAt: new Date('2024-03-25').toISOString(),
            updatedAt: new Date('2024-03-25').toISOString(),
        },
        {
            name: 'Almo Nature Holistic Adult Chicken & Rice 2kg',
            price: 18.99,
            weight: '2kg',
            badge: 'Holistic',
            rating: 4.7,
            category: 'Crocchette',
            subcategory: 'Holistic',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Almo Nature',
            breed: 'Maine Coon',
            intolerances: [],
            tags: ['Holistic', 'Pollo', 'Riso'],
            ingredients: 'Pollo fresco (26%), riso (14%), mais, polpa di barbabietola. Proteine: 32%',
            benefits: ['Ingredienti freschi', 'Digestione facile', 'Pelo lucido'],
            contraindications: null,
            usage: 'Gatti adulti: 50-70g al giorno',
            createdAt: new Date('2024-03-28').toISOString(),
            updatedAt: new Date('2024-03-28').toISOString(),
        },
        {
            name: 'Purina Pro Plan Sterilised Salmon 10kg',
            price: 44.50,
            weight: '10kg',
            badge: 'Sterilised',
            rating: 4.6,
            category: 'Crocchette',
            subcategory: 'Sterilised',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Purina Pro Plan',
            breed: 'Siamese',
            intolerances: [],
            tags: ['Sterilizzati', 'Salmone', 'Controllo peso'],
            ingredients: 'Salmone (14%), riso, proteine di pollo disidratate, glutine di mais. Proteine: 41%',
            benefits: ['Controllo peso', 'Salute urinaria', 'Alto contenuto proteico'],
            contraindications: 'Solo per gatti sterilizzati',
            usage: 'Gatti sterilizzati: 40-55g al giorno',
            createdAt: new Date('2024-04-01').toISOString(),
            updatedAt: new Date('2024-04-01').toISOString(),
        },
        {
            name: 'Orijen Cat & Kitten 5.4kg',
            price: 67.90,
            weight: '5.4kg',
            badge: 'Premium',
            rating: 4.9,
            category: 'Crocchette',
            subcategory: 'Biologically Appropriate',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Orijen',
            breed: 'British Shorthair',
            intolerances: ['Cereali'],
            tags: ['Biologico', 'Grain Free', 'Premium'],
            ingredients: 'Pollo fresco (15%), tacchino fresco (7%), pesce intero (4%), fegato di pollo. Proteine: 40%',
            benefits: ['Dieta ancestrale', 'Alto contenuto proteico', 'Ingredienti regionali'],
            contraindications: null,
            usage: 'Gatti adulti: 30-60g al giorno',
            createdAt: new Date('2024-04-03').toISOString(),
            updatedAt: new Date('2024-04-03').toISOString(),
        },
        {
            name: 'Farmina N&D Quinoa Urinary Duck 1.5kg',
            price: 21.90,
            weight: '1.5kg',
            badge: 'Functional',
            rating: 4.8,
            category: 'Crocchette',
            subcategory: 'Functional',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Farmina',
            breed: 'Ragdoll',
            intolerances: ['Cereali'],
            tags: ['Quinoa', 'Urinario', 'Anatra'],
            ingredients: 'Anatra fresca (20%), quinoa (8%), semi di lino, olio di cocco, mirtilli. Proteine: 33%',
            benefits: ['Salute urinaria', 'Superfood quinoa', 'Antiossidanti naturali'],
            contraindications: null,
            usage: 'Gatti adulti: 45-65g al giorno',
            createdAt: new Date('2024-04-05').toISOString(),
            updatedAt: new Date('2024-04-05').toISOString(),
        },
        {
            name: 'Hill\'s Science Plan Adult Hairball 1.5kg',
            price: 19.90,
            weight: '1.5kg',
            badge: 'Science',
            rating: 4.5,
            category: 'Crocchette',
            subcategory: 'Hairball',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Hill\'s',
            breed: 'Persiano',
            intolerances: [],
            tags: ['Hairball', 'Scientifico', 'Boli pelo'],
            ingredients: 'Pollo, riso integrale, mais, polpa di barbabietola, cellulosa. Proteine: 33%',
            benefits: ['Riduce boli di pelo', 'Digestione sana', 'Nutrizione clinica'],
            contraindications: null,
            usage: 'Gatti adulti pelo lungo: 50-70g al giorno',
            createdAt: new Date('2024-04-08').toISOString(),
            updatedAt: new Date('2024-04-08').toISOString(),
        },
        {
            name: 'Acana Grasslands Cat 1.8kg',
            price: 28.90,
            weight: '1.8kg',
            badge: 'Regional',
            rating: 4.7,
            category: 'Crocchette',
            subcategory: 'Regional',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Acana',
            breed: 'Maine Coon',
            intolerances: ['Cereali'],
            tags: ['Grasslands', 'Agnello', 'Regional'],
            ingredients: 'Agnello fresco (8%), farina di agnello (8%), piselli gialli, lenticchie rosse. Proteine: 37%',
            benefits: ['Ingredienti regionali', 'Ricco di carne', 'Limited ingredients'],
            contraindications: null,
            usage: 'Gatti adulti: 40-75g al giorno',
            createdAt: new Date('2024-04-10').toISOString(),
            updatedAt: new Date('2024-04-10').toISOString(),
        },
        {
            name: 'Monge Natural Superpremium Sterilised 1.5kg',
            price: 16.90,
            weight: '1.5kg',
            badge: null,
            rating: 4.4,
            category: 'Crocchette',
            subcategory: 'Sterilised',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Monge',
            breed: 'British Shorthair',
            intolerances: [],
            tags: ['Sterilizzati', 'Natural', 'Italiano'],
            ingredients: 'Pollo fresco (10%), riso, mais, polpa di barbabietola, olio di pollo. Proteine: 32%',
            benefits: ['Made in Italy', 'Controllo peso', 'Ingredienti naturali'],
            contraindications: null,
            usage: 'Gatti sterilizzati: 45-60g al giorno',
            createdAt: new Date('2024-04-12').toISOString(),
            updatedAt: new Date('2024-04-12').toISOString(),
        },

        // Cats - Cibo Umido (7 products)
        {
            name: 'Almo Nature Legend Tuna in Jelly 70g',
            price: 1.89,
            weight: '70g',
            badge: 'Legend',
            rating: 4.8,
            category: 'Cibo Umido',
            subcategory: 'Legend',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Almo Nature',
            breed: null,
            intolerances: [],
            tags: ['Legend', 'Tonno', 'Gelatina'],
            ingredients: 'Tonno (51%), brodo di cottura, gelatina naturale. Proteine: 17%',
            benefits: ['Alto contenuto di pesce', 'Idratazione', 'Naturale 100%'],
            contraindications: null,
            usage: 'Gatti adulti: 2-3 lattine al giorno',
            createdAt: new Date('2024-04-15').toISOString(),
            updatedAt: new Date('2024-04-15').toISOString(),
        },
        {
            name: 'Royal Canin Instinctive in Gravy 85g',
            price: 2.20,
            weight: '85g',
            badge: 'Instinctive',
            rating: 4.7,
            category: 'Cibo Umido',
            subcategory: 'Instinctive',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Royal Canin',
            breed: null,
            intolerances: [],
            tags: ['Instinctive', 'Sugo', 'Bilanciato'],
            ingredients: 'Carne e sottoprodotti, cereali, sottoprodotti vegetali, sugo. Proteine: 12%',
            benefits: ['Profilo nutrizionale ottimale', 'Texture irresistibile', 'Salute urinaria'],
            contraindications: null,
            usage: 'Gatti adulti: 3-4 bustine al giorno',
            createdAt: new Date('2024-04-18').toISOString(),
            updatedAt: new Date('2024-04-18').toISOString(),
        },
        {
            name: 'Whiskas Adult Pollo in Gelatina 85g',
            price: 1.50,
            weight: '85g',
            badge: null,
            rating: 4.3,
            category: 'Cibo Umido',
            subcategory: 'Adult',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Whiskas',
            breed: null,
            intolerances: [],
            tags: ['Pollo', 'Gelatina', 'Conveniente'],
            ingredients: 'Carne e sottoprodotti (4% pollo), cereali, gelatina, minerali. Proteine: 8%',
            benefits: ['Prezzo conveniente', 'Gusto apprezzato', 'Facile digestione'],
            contraindications: null,
            usage: 'Gatti adulti: 3-4 bustine al giorno',
            createdAt: new Date('2024-04-20').toISOString(),
            updatedAt: new Date('2024-04-20').toISOString(),
        },
        {
            name: 'Schesir Natural Tonno con Gamberi 85g',
            price: 2.80,
            weight: '85g',
            badge: 'Natural',
            rating: 4.9,
            category: 'Cibo Umido',
            subcategory: 'Natural',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Schesir',
            breed: null,
            intolerances: [],
            tags: ['Natural', 'Tonno', 'Gamberi'],
            ingredients: 'Tonno (51%), gamberi (5%), brodo di cottura. Proteine: 16%',
            benefits: ['Ingredienti nobili', 'Naturale al 100%', 'Gusto del mare'],
            contraindications: null,
            usage: 'Gatti adulti: 2-3 lattine al giorno',
            createdAt: new Date('2024-04-22').toISOString(),
            updatedAt: new Date('2024-04-22').toISOString(),
        },
        {
            name: 'Purina Felix Doppio Gusto Manzo e Pollo 85g',
            price: 1.65,
            weight: '85g',
            badge: 'Doppio Gusto',
            rating: 4.5,
            category: 'Cibo Umido',
            subcategory: 'Felix',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Purina Felix',
            breed: null,
            intolerances: [],
            tags: ['Doppio gusto', 'Manzo', 'Pollo'],
            ingredients: 'Carne e sottoprodotti (manzo 4%, pollo 4%), cereali, minerali. Proteine: 13%',
            benefits: ['Due gusti in uno', 'Texture appetitosa', 'Nutrizione completa'],
            contraindications: null,
            usage: 'Gatti adulti: 3-4 bustine al giorno',
            createdAt: new Date('2024-04-25').toISOString(),
            updatedAt: new Date('2024-04-25').toISOString(),
        },
        {
            name: 'Trainer Natural Adult Salmone 85g',
            price: 1.95,
            weight: '85g',
            badge: 'Natural',
            rating: 4.6,
            category: 'Cibo Umido',
            subcategory: 'Natural',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Trainer',
            breed: null,
            intolerances: [],
            tags: ['Natural', 'Salmone', 'Italiano'],
            ingredients: 'Salmone (4%), brodo naturale, riso, minerali, vitamine. Proteine: 11%',
            benefits: ['Omega-3', 'Ingredienti naturali', 'Made in Italy'],
            contraindications: null,
            usage: 'Gatti adulti: 3-4 bustine al giorno',
            createdAt: new Date('2024-04-28').toISOString(),
            updatedAt: new Date('2024-04-28').toISOString(),
        },
        {
            name: 'Gourmet Gold Mousse Tacchino 85g',
            price: 2.10,
            weight: '85g',
            badge: 'Gourmet',
            rating: 4.7,
            category: 'Cibo Umido',
            subcategory: 'Gourmet',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Gourmet',
            breed: null,
            intolerances: [],
            tags: ['Gourmet', 'Mousse', 'Tacchino'],
            ingredients: 'Carne e sottoprodotti (tacchino 4%), sottoprodotti vegetali, minerali. Proteine: 11%',
            benefits: ['Texture mousse', 'Gusto raffinato', 'Esperienza gourmet'],
            contraindications: null,
            usage: 'Gatti adulti: 3-4 lattine al giorno',
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-05-01').toISOString(),
        },

        // Cats - Snack (2 products)
        {
            name: 'Dreamies Adult Pollo 60g',
            price: 3.20,
            weight: '60g',
            badge: 'Irresistibili',
            rating: 4.8,
            category: 'Snack',
            subcategory: 'Treats',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Dreamies',
            breed: null,
            intolerances: [],
            tags: ['Dreamies', 'Pollo', 'Croccanti'],
            ingredients: 'Cereali, carne e sottoprodotti (pollo 4%), oli e grassi, minerali. Proteine: 22%',
            benefits: ['Croccanti fuori morbidi dentro', 'Irresistibili', 'Perfetti come premio'],
            contraindications: 'Max 20 pezzi al giorno',
            usage: 'Dare come premio, max 20% della razione giornaliera',
            createdAt: new Date('2024-05-03').toISOString(),
            updatedAt: new Date('2024-05-03').toISOString(),
        },
        {
            name: 'Greenies Feline Dental Treats Salmone 60g',
            price: 8.90,
            weight: '60g',
            badge: 'Dental',
            rating: 4.6,
            category: 'Snack',
            subcategory: 'Dental',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Greenies',
            breed: null,
            intolerances: [],
            tags: ['Dental', 'Salmone', 'Igiene orale'],
            ingredients: 'Pollo, riso integrale, farina di salmone, avena, minerali. Proteine: 30%',
            benefits: ['Igiene dentale', 'Riduce tartaro', 'Alito fresco'],
            contraindications: null,
            usage: 'Gatti adulti: 5-10 pezzi al giorno',
            createdAt: new Date('2024-05-05').toISOString(),
            updatedAt: new Date('2024-05-05').toISOString(),
        },

        // Cats - Integratori (2 products)
        {
            name: 'Royal Canin Hairball Care Paste 70g',
            price: 16.90,
            weight: '70g',
            badge: 'Hairball',
            rating: 4.6,
            category: 'Integratori',
            subcategory: 'Hairball',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Royal Canin',
            breed: null,
            intolerances: [],
            tags: ['Hairball', 'Pasta', 'Boli pelo'],
            ingredients: 'Oli e grassi, sottoprodotti vegetali, estratti vegetali, lieviti',
            benefits: ['Elimina boli di pelo', 'Transito intestinale', 'Gusto appetibile'],
            contraindications: null,
            usage: 'Gatti adulti: 2-6cm di pasta al giorno',
            createdAt: new Date('2024-05-08').toISOString(),
            updatedAt: new Date('2024-05-08').toISOString(),
        },
        {
            name: 'Beaphar Pasta Malt per Gatti 100g',
            price: 12.50,
            weight: '100g',
            badge: null,
            rating: 4.4,
            category: 'Integratori',
            subcategory: 'Malt',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Beaphar',
            breed: null,
            intolerances: [],
            tags: ['Malt', 'Pasta', 'Digestione'],
            ingredients: 'Estratto di malto, oli e grassi, sottoprodotti del latte, cellulosa',
            benefits: ['Facilita eliminazione pelo', 'Digestione naturale', 'Prevenzione costipazione'],
            contraindications: null,
            usage: 'Gatti adulti: 1-2 cucchiaini al giorno',
            createdAt: new Date('2024-05-10').toISOString(),
            updatedAt: new Date('2024-05-10').toISOString(),
        },

        // Cats - Giochi (1 product)
        {
            name: 'Trixie Pallina con Piume e Campanellino',
            price: 4.90,
            weight: '15g',
            badge: null,
            rating: 4.7,
            category: 'Giochi',
            subcategory: 'Interactive',
            animal: 'Gatti',
            age: 'adulto',
            brand: 'Trixie',
            breed: null,
            intolerances: [],
            tags: ['Interattivo', 'Piume', 'Campanellino'],
            ingredients: 'Sisal naturale, piume vere, campanellino metallico',
            benefits: ['Stimola istinto caccia', 'Esercizio fisico', 'Divertimento assicurato'],
            contraindications: 'Sorvegliare durante il gioco',
            usage: 'Gioco interattivo sotto supervisione',
            createdAt: new Date('2024-05-12').toISOString(),
            updatedAt: new Date('2024-05-12').toISOString(),
        }
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully - 50 premium pet food products inserted');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});